# Generated by Django 3.1.7 on 2021-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=11)),
                ('email_id', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100, null=True)),
                ('family_mem', models.IntegerField(default=0)),
                ('mem_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
