# Generated by Django 3.1.7 on 2021-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cus_app', '0002_customer_service_provided'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Service_Provided',
            new_name='Diagnostic',
        ),
        migrations.AddField(
            model_name='customer',
            name='Medicine_sold',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Surgical_or_consultation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Visit_for_Queries',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
