# Generated by Django 3.1.7 on 2021-09-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cus_app', '0003_auto_20210922_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Diagnostic',
            new_name='diagnostic',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Medicine_sold',
            new_name='medicine_sold',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Surgical_or_consultation',
            new_name='surgical_or_consultation',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Visit_for_Queries',
            new_name='visit_for_Queries',
        ),
    ]
