# Generated by Django 3.2.7 on 2021-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cus_app', '0010_auto_20210922_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
